name: Deploy GitHub Pages

on:
  push:
    branches:
      - master  # or 'main', depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable credential persistence

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # Explicitly set the branch for GitHub Pages
          commit_message: "Deploy to GitHub Pages"
